// <auto-generated />
using System;
using EventFlowAPI.DB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventFlowAPI.DB.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20240817163147_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventFlowAPI.DB.Entities.AdditionalServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMERIC(6,2)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalServices");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DefaultHallId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HallId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EventCategory");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LongDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("EventDetails");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("NUMERIC(6,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PassTypeId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EventPass");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventPassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMERIC(6,2)");

                    b.Property<decimal>("ValidityPeriodInMonths")
                        .HasColumnType("NUMERIC(2)");

                    b.HasKey("Id");

                    b.ToTable("EventPassType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMERIC(5,2)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("EventTicket");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Festival");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.FestivalDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LongDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("FestivalDetails");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_Event", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("FestivalId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Festival_Event");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_MediaPatron", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("int");

                    b.Property<int>("MediaPatronId")
                        .HasColumnType("int");

                    b.HasKey("FestivalId", "MediaPatronId");

                    b.HasIndex("MediaPatronId");

                    b.ToTable("Festival_MediaPatron");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_Organizer", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.HasKey("FestivalId", "OrganizerId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Festival_Organizer");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_Sponsor", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("int");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.HasKey("FestivalId", "SponsorId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Festival_Sponsor");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Floor")
                        .HasColumnType("NUMERIC(1)");

                    b.Property<int>("HallNr")
                        .HasColumnType("int");

                    b.Property<int>("HallTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCopy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxNumberOfSeats")
                        .HasColumnType("NUMERIC(3)");

                    b.Property<decimal>("MaxNumberOfSeatsColumns")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("MaxNumberOfSeatsRows")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("NumberOfSeats")
                        .HasColumnType("NUMERIC(3)");

                    b.Property<decimal>("NumberOfSeatsColumns")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("NumberOfSeatsRows")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("RentalPricePerHour")
                        .HasColumnType("NUMERIC(5,2)");

                    b.Property<decimal?>("StageArea")
                        .HasColumnType("NUMERIC(5,2)");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("NUMERIC(5,2)");

                    b.Property<decimal>("TotalLength")
                        .HasColumnType("NUMERIC(4,2)");

                    b.Property<decimal>("TotalWidth")
                        .HasColumnType("NUMERIC(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallTypeId");

                    b.ToTable("Hall");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallRent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("NUMERIC(7,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("HallRent");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallRent_AdditionalServices", b =>
                {
                    b.Property<int>("HallRentId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalServicesId")
                        .HasColumnType("int");

                    b.HasKey("HallRentId", "AdditionalServicesId");

                    b.HasIndex("AdditionalServicesId");

                    b.ToTable("HallRent_AdditionalServices");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("HallType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallType_Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("HallTypeId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "HallTypeId");

                    b.HasIndex("HallTypeId");

                    b.ToTable("HallType_Equipment");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.MediaPatron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MediaPatron");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Organizer");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PaymentType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndOfReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTicketId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("NUMERIC(7,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartOfReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventTicketId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Reservation_Seat", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("Reservation_Seat");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Column")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("GridColumn")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("GridRow")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<decimal>("Row")
                        .HasColumnType("NUMERIC(2)");

                    b.Property<decimal>("SeatNr")
                        .HasColumnType("NUMERIC(3)");

                    b.Property<int>("SeatTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("SeatTypeId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.SeatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddtionalPaymentPercentage")
                        .HasColumnType("NUMERIC(4,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SeatType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sponsor");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("TicketType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("FlatNumber")
                        .HasColumnType("NUMERIC(3)");

                    b.Property<decimal>("HouseNumber")
                        .HasColumnType("NUMERIC(3)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Event", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.EventCategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.Hall", "Hall")
                        .WithMany("Events")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.EventDetails", "Details")
                        .WithOne("Event")
                        .HasForeignKey("EventFlowAPI.DB.Entities.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Details");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventPass", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.EventPassType", "PassType")
                        .WithMany("EventPasses")
                        .HasForeignKey("PassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.PaymentType", "PaymentType")
                        .WithMany("EventPasses")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.User", "User")
                        .WithMany("EventPasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassType");

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventTicket", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.FestivalDetails", "Details")
                        .WithOne("Festival")
                        .HasForeignKey("EventFlowAPI.DB.Entities.Festival", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_Event", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_MediaPatron", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.MediaPatron", null)
                        .WithMany()
                        .HasForeignKey("MediaPatronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_Organizer", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Festival_Sponsor", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Hall", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.HallType", "Type")
                        .WithMany("Halls")
                        .HasForeignKey("HallTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallRent", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Hall", "Hall")
                        .WithMany("Rents")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.PaymentType", "PaymentType")
                        .WithMany("HallRents")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.User", "User")
                        .WithMany("HallRents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallRent_AdditionalServices", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.AdditionalServices", null)
                        .WithMany()
                        .HasForeignKey("AdditionalServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.HallRent", null)
                        .WithMany()
                        .HasForeignKey("HallRentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallType_Equipment", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.HallType", null)
                        .WithMany()
                        .HasForeignKey("HallTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Reservation", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.EventTicket", "Ticket")
                        .WithMany("Reservations")
                        .HasForeignKey("EventTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.PaymentType", "PaymentType")
                        .WithMany("Reservations")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Reservation_Seat", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Seat", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventFlowAPI.DB.Entities.SeatType", "SeatType")
                        .WithMany("Seats")
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("SeatType");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.User", b =>
                {
                    b.HasOne("EventFlowAPI.DB.Entities.UserData", "UserData")
                        .WithOne("User")
                        .HasForeignKey("EventFlowAPI.DB.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventDetails", b =>
                {
                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventPassType", b =>
                {
                    b.Navigation("EventPasses");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.EventTicket", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.FestivalDetails", b =>
                {
                    b.Navigation("Festival");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.Hall", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Rents");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.HallType", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.PaymentType", b =>
                {
                    b.Navigation("EventPasses");

                    b.Navigation("HallRents");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.SeatType", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.User", b =>
                {
                    b.Navigation("EventPasses");

                    b.Navigation("HallRents");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EventFlowAPI.DB.Entities.UserData", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
