using EventFlowAPI.DB.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventFlowAPI.DB.Extensions.SeedingExtensions
{
    public static class HallDetailsSeedExtentions
    {
        public static void Seed(this EntityTypeBuilder<HallDetails> entityBuilder)
        {
            entityBuilder.HasData(
               new HallDetails
               {
                   Id = 1,
                   TotalLength = 20m,
                   TotalWidth = 40m,
                   TotalArea = 800m,
                   StageWidth = 20f,
                   StageLength = 4f,
                   //NumberOfSeatsRows = 10,
                   MaxNumberOfSeatsRows = 15,
                   //NumberOfSeatsColumns = 10,
                   MaxNumberOfSeatsColumns = 15,
                   NumberOfSeats = 100,
                   MaxNumberOfSeats = 255,
               },
               new HallDetails
               {
                   Id = 2,
                   TotalLength = 15m,
                   TotalWidth = 10m,
                   TotalArea = 150m,
                   StageWidth = null,
                   StageLength = null,
                   //NumberOfSeatsRows = 15,
                   MaxNumberOfSeatsRows = 15,
                   //NumberOfSeatsColumns = 10,
                   MaxNumberOfSeatsColumns = 10,
                   NumberOfSeats = 150,
                   MaxNumberOfSeats = 150,
               },
               new HallDetails
               {
                   Id = 3,
                   TotalLength = 10m,
                   TotalWidth = 8m,
                   TotalArea = 80m,
                   StageWidth = 5f,
                   StageLength = 4f,
                   //NumberOfSeatsRows = 6,
                   MaxNumberOfSeatsRows = 6,
                   //NumberOfSeatsColumns = 10,
                   MaxNumberOfSeatsColumns = 10,
                   NumberOfSeats = 60,
                   MaxNumberOfSeats = 60,
               },
               new HallDetails
               {
                   Id = 4,
                   TotalLength = 14m,
                   TotalWidth = 10m,
                   TotalArea = 140m,
                   StageWidth = 8f,
                   StageLength = 5f,
                   //NumberOfSeatsRows = 10,
                   MaxNumberOfSeatsRows = 10,
                   //NumberOfSeatsColumns = 10,
                   MaxNumberOfSeatsColumns = 10,
                   NumberOfSeats = 100,
                   MaxNumberOfSeats = 100,
               },
                new HallDetails
                {
                    Id = 5,
                    TotalLength = 20m,
                    TotalWidth = 40m,
                    TotalArea = 800m,
                    StageWidth = 20f,
                    StageLength = 4f,
                    //NumberOfSeatsRows = 10,
                    MaxNumberOfSeatsRows = 15,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 15,
                    NumberOfSeats = 100,
                    MaxNumberOfSeats = 255,
                },
                new HallDetails
                {
                    Id = 6,
                    TotalLength = 15m,
                    TotalWidth = 10m,
                    TotalArea = 150m,
                    StageWidth = null,
                    StageLength = null,
                    //NumberOfSeatsRows = 15,
                    MaxNumberOfSeatsRows = 15,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 150,
                    MaxNumberOfSeats = 150,
                },
                new HallDetails
                {
                    Id = 7,
                    TotalLength = 10m,
                    TotalWidth = 8m,
                    TotalArea = 80m,
                    StageWidth = 5f,
                    StageLength = 4f,
                    //NumberOfSeatsRows = 6,
                    MaxNumberOfSeatsRows = 6,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 60,
                    MaxNumberOfSeats = 60,
                },
                new HallDetails
                {
                    Id = 8,
                    TotalLength = 14m,
                    TotalWidth = 10m,
                    TotalArea = 140m,
                    StageWidth = 8f,
                    StageLength = 5f,
                    //NumberOfSeatsRows = 10,
                    MaxNumberOfSeatsRows = 10,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 100,
                    MaxNumberOfSeats = 100,
                },
                new HallDetails
                {
                    Id = 9,
                    TotalLength = 20m,
                    TotalWidth = 40m,
                    TotalArea = 800m,
                    StageWidth = 20f,
                    StageLength = 4f,
                    //NumberOfSeatsRows = 10,
                    MaxNumberOfSeatsRows = 15,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 15,
                    NumberOfSeats = 100,
                    MaxNumberOfSeats = 255,
                },
                new HallDetails
                {
                    Id = 10,
                    TotalLength = 15m,
                    TotalWidth = 10m,
                    TotalArea = 150m,
                    StageWidth = null,
                    StageLength = null,
                    //NumberOfSeatsRows = 15,
                    MaxNumberOfSeatsRows = 15,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 150,
                    MaxNumberOfSeats = 150,
                },
                new HallDetails
                {
                    Id = 11,
                    TotalLength = 14m,
                    TotalWidth = 10m,
                    TotalArea = 140m,
                    StageWidth = 8f,
                    StageLength = 5f,
                    //NumberOfSeatsRows = 10,
                    MaxNumberOfSeatsRows = 10,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 100,
                    MaxNumberOfSeats = 100,
                },
                new HallDetails
                {
                    Id = 12,
                    TotalLength = 20m,
                    TotalWidth = 40m,
                    TotalArea = 800m,
                    StageWidth = 20f,
                    StageLength = 4f,
                    //NumberOfSeatsRows = 10,
                    MaxNumberOfSeatsRows = 15,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 15,
                    NumberOfSeats = 100,
                    MaxNumberOfSeats = 255,
                },
                new HallDetails
                {
                    Id = 13,
                    TotalLength = 15m,
                    TotalWidth = 10m,
                    TotalArea = 150m,
                    StageWidth = null,
                    StageLength = null,
                    //NumberOfSeatsRows = 15,
                    MaxNumberOfSeatsRows = 15,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 150,
                    MaxNumberOfSeats = 150,
                },
                new HallDetails
                {
                    Id = 14,
                    TotalLength = 10m,
                    TotalWidth = 8m,
                    TotalArea = 80m,
                    StageWidth = 5f,
                    StageLength = 4f,
                    //NumberOfSeatsRows = 6,
                    MaxNumberOfSeatsRows = 6,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 60,
                    MaxNumberOfSeats = 60,
                },
                new HallDetails
                {
                    Id = 15,
                    TotalLength = 14m,
                    TotalWidth = 10m,
                    TotalArea = 140m,
                    StageWidth = 8f,
                    StageLength = 5f,
                    //NumberOfSeatsRows = 10,
                    MaxNumberOfSeatsRows = 10,
                    //NumberOfSeatsColumns = 10,
                    MaxNumberOfSeatsColumns = 10,
                    NumberOfSeats = 100,
                    MaxNumberOfSeats = 100,
                }
           );
        }
    }
}
